---
title: "Illustrating purrr"
author: "Mick Cooney <mickcooney@gmail.com>"
date: "13 July 2016"
output:
  html_document:
    fig_caption: yes
    theme: spacelab #sandstone #spacelab #flatly
    highlight: pygments
    number_sections: TRUE
    toc: TRUE
    toc_depth: 2
    toc_float:
      smooth_scroll: FALSE
  pdf_document: default
---


```{r knit_opts, include = FALSE}
knitr::opts_chunk$set(tidy       = FALSE,
                      cache      = FALSE,
                      fig.height =     8,
                      fig.width  =    11
                     )

library(tidyverse)
library(furrr)
library(broom)

plan(multisession)

set.seed(42)
```


```{r load_data, echo=TRUE}
policyclaim_tbl <- read_rds("data/policyclaim_tbl.rds")

training_tbl <- policyclaim_tbl %>%
  sample_n(20000) %>%
  arrange(policy_id)

claimdata_tbl <- training_tbl %>%
  unnest(claim_data)



pricing_policies_tbl <- policyclaim_tbl %>%
  anti_join(training_tbl, by = "policy_id") %>% 
  sample_n(10000)
```


```{r fit_freq_sev_models, echo=TRUE}
freq_model_01 <- glm(claim_count ~ cat_driver_age + region + fuel,
                     offset = log(exposure),
                     family = poisson,
                     data   = training_tbl)


freq_model_02 <- glm(claim_count ~ cat_driver_age + region + fuel + cat_car_age,
                     offset = log(exposure),
                     family = poisson,
                     data   = training_tbl)

sev_model_01 <- glm(claim_amount ~ 1,
                    family = Gamma(link = 'log'),
                    data   = claimdata_tbl)

sev_model_02 <- glm(claim_amount ~ region,
                    family = Gamma(link = 'log'),
                    data   = claimdata_tbl)



create_pricing_function <- function(freq_model, sev_model) {
  
  price_func <- function(policydata_tbl) {
    freqrate_tbl <- freq_model %>%
      augment(newdata = policydata_tbl, type.predict = "response") %>%
      select(policy_id, freq_rate = .fitted)
        
    sevamt_tbl <- sev_model %>%
      augment(newdata = policydata_tbl, type.predict = "response") %>%
      select(policy_id, sev_amt = .fitted)
    
    pricing_tbl <- freqrate_tbl %>%
      inner_join(sevamt_tbl, by = "policy_id") %>%
      mutate(price = freq_rate * sev_amt)
    
    return(pricing_tbl)
  }
  
  return(price_func)
}


one_pricer <- create_pricing_function(freq_model_01, sev_model_01)
two_pricer <- create_pricing_function(freq_model_01, sev_model_02)


create_freq_fitter <- function(freq_formula, training_tbl) {
  freq_model <- glm(freq_formula,
                    offset = log(exposure),
                    family = poisson,
                    data   = training_tbl)
  
  return(freq_model)
}


create_sev_fitter <- function(sev_formula) {
  sev_model <- glm(sev_formula,
                   family = Gamma(link = 'log'),
                   data   = claimdata_tbl)
  
  return(sev_model)
}


freq_form <- c("claim_count ~ 1",
               "claim_count ~ cat_driver_age",
               "claim_count ~ cat_driver_age + region",
               "claim_count ~ cat_driver_age + region + fuel",
               "claim_count ~ cat_driver_age + region + fuel + cat_driver_age:region")

freq_models_tbl <- tibble(freq_form = map(freq_form, as.formula)) %>%
  mutate(fit_freq_model = future_map(freq_form, create_freq_fitter, training_tbl = training_tbl))

sev_form <- c("claim_amount ~ 1",
              "claim_amount ~ region",
              "claim_amount ~ cat_driver_age",
              "claim_amount ~ cat_driver_age + region")

sev_models_tbl <- tibble(sev_form = map(sev_form, as.formula)) %>%
  mutate(fit_sev_model = map(sev_form, create_sev_fitter))


allmodels_tbl <- freq_models_tbl %>%
  mutate(joinid = 1) %>%
  inner_join(sev_models_tbl %>% mutate(joinid = 1), by = 'joinid') %>%
  select(-joinid) %>%
  mutate(pricer = map2(fit_freq_model, fit_sev_model, create_pricing_function)) %>%
  mutate(price_tbl     = map(pricer, exec, policydata_tbl = pricing_policies_tbl)) %>%
  mutate(freq_form_str = freq_form %>% as.character(),
         sev_form_str  = sev_form  %>% as.character())


mod_unnest_tbl <- allmodels_tbl %>%
  select(freq_form_str, sev_form_str, price_tbl) %>%
  unnest(price_tbl)
```


# Create Simulations

```{r build_simulations, echo=TRUE}
construct_simulation_data <- function(freq_model, sev_model, policy_tbl, n_sim = 1000) {
  
  # illustration_sim_tbl <- freq_model %>%
  #   augment(newdata = policy_tbl, type.predict = "response") %>%
  #   select(policy_id, freq_mean = .fitted) %>%
  #   mutate(sim_count = rpois(n(), lambda = freq_mean))

  create_sim <- ~ rnorm(n_sim, mean = .x, sd = .y) %>%
    enframe(name = "sim_id", value = "sim_lambda") %>%
    mutate(sim_lambda = pmax(0.00001, sim_lambda)) %>%
    mutate(sim_count = rpois(n(), lambda = sim_lambda))
  
  
  freq_sim_tbl <- freq_model %>%
    augment(newdata = policy_tbl, type.predict = "response") %>%
    select(policy_id, freq_mean = .fitted, freq_sd = .se.fit) %>%
    mutate(sim_data = map2(freq_mean, freq_sd, create_sim))
  
  return(freq_sim_tbl)
}

obs_cases <- training_tbl %>% pull(claim_count) %>% sum()

simdata_tbl <- construct_simulation_data(freq_model_02, sev_model_02, training_tbl) %>%
  select(policy_id, sim_data) %>%
  unnest(sim_data) %>%
  group_by(sim_id) %>%
  summarise(total_cases = sum(sim_count))

ggplot(simdata_tbl) +
  geom_histogram(aes(x = total_cases), bins = 50) +
  geom_vline(aes(xintercept = obs_cases), colour = "red")



```

